name: Build with Dockerfile no Github Actions

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  PROJECT_NAME: hello_world
  VERSION: 0.0.1.${{ github.run_id }}
  TARGET: x86_64-pc-windows-gnu

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t "${{ env.PROJECT_NAME }}:${{ env.VERSION }}" -f Dockerfile .

    - name: Get build artifacts
      run: |
        mkdir -p artifacts
        docker create --name "artifacts_${{ github.run_id }}" "${{ env.PROJECT_NAME }}:${{ env.VERSION }}"
        docker export "artifacts_${{ github.run_id }}" | tar t
        docker cp "artifacts_${{ github.run_id }}":/app/target/${{ env.TARGET }}/release/* artifacts/
        docker rm "artifacts_${{ github.run_id }}"
        docker rmi "${{ env.PROJECT_NAME }}:${{ env.VERSION }}"
        find ./artifacts

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PROJECT_NAME }}
        path: |
          ./artfacts/*.exe
        retention-days: 1
        overwrite: true
