name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  VERSION: 0.0.1.${{ github.run_id }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Prepare environment
      run: |
        apt-get update
        apt-get -y install gcc-mingw-w64    
    
    - uses: actions/checkout@v4
    
    - name: Build
      run: | 
        echo "Version: ${{ env.VERSION }}"
        rustup target add x86_64-pc-windows-gnu
        cargo build --target x86_64-pc-windows-gnu --release

    # - uses: actions/upload-artifact@v4
    #   with:
    #     name: hello-world-
    #     path: path/to/artifact/world.txt

